l_braz_por:
 com_topbar_configuration_button_tooltip: "Abrir Configurações da Barra Superior"
 com_topbar_configuration_title: "Configurações da Barra Superior"
 com_topbar_configuration_current: "Barra Superior Atual"
 com_topbar_configuration_add: "Editar Barra Superior"
 com_topbar_configuration_always_show: "Sempre mostrar elementos da barra superior (#r Sobrepõe Janelas#!)"
 com_topbar_configuration_add_explanation: "Adicione ou remova elementos da barra superior usando os botões abaixo."
 com_topbar_configuration_clear_first_tooltip: "Limpar a primeira linha da barra superior."
 com_topbar_configuration_add_first_tooltip: "Adicionar este elemento à primeira linha da barra superior."
 com_topbar_configuration_remove_first_tooltip: "Remova este elemento da primeira linha da barra superior."
 com_topbar_configuration_clear_second_tooltip: "Limpar a segunda linha da barra superior."
 com_topbar_configuration_add_second_tooltip: "Adicionar este elemento à segunda linha da barra superior."
 com_topbar_configuration_remove_second_tooltip: "Remova este elemento da segunda linha da barra superior."
 com_topbar_configuration_add_header_source: "Fonte do Elemento"
 com_topbar_configuration_add_header_element: "Elemento da Barra Superior"
 com_topbar_configuration_add_header_first: "Primeira\nLinha"
 com_topbar_configuration_add_header_second: "Segunda\nLinha"